import type { Metadata } from "next"
import "./globals.css"
import { montrealBook } from "./font"
import CustomLayout from "@/components/Layout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montrealBook.className} antialiased`}>
        <CustomLayout>{children}</CustomLayout>
      </body>
    </html>
  )
}
